apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubequest-app.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubequest-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_KEY: {{ .Values.secrets.appKey | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  DB_ROOT_PASSWORD: {{ .Values.secrets.dbRootPassword | quote }}
  # MySQL Bitnami attend aussi ces clés
  mysql-password: {{ .Values.secrets.dbPassword | quote }}
  mysql-root-password: {{ .Values.secrets.dbRootPassword | quote }}
