apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubequest-staging

helmGlobals:
  chartHome: ../../../

helmCharts:
  - name: helm-chart
    releaseName: kubequest-app
    namespace: kubequest-staging
    valuesFile: values.yaml

resources:
  - namespace.yaml

commonLabels:
  environment: staging
