apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth

helmCharts:
  - name: dex
    repo: https://charts.dexidp.io
    version: "0.24.0"
    releaseName: dex
    namespace: auth
    valuesFile: values-dex.yaml

  - name: oauth2-proxy
    repo: https://oauth2-proxy.github.io/manifests
    version: "10.4.3"
    releaseName: oauth2-proxy
    namespace: auth
    valuesFile: values-oauth2-proxy.yaml

resources:
  - namespace.yaml
