apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

commonLabels:
  environment: production

patches:
  # Production : plus de rétention Prometheus
  - target:
      kind: HelmChart
      name: kube-prometheus-stack
    patch: |-
      - op: replace
        path: /spec/values/prometheus/prometheusSpec/retention
        value: 30d
