controller:
  replicaCount: 1

  # Écoute directement sur les ports 80/443 du nœud ingress (pas de klipper-lb)
  hostNetwork: true
  hostPort:
    enabled: true

  # Forcer le déploiement sur le nœud dédié "ingress"
  nodeSelector:
    node-role: ingress

  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "ingress"
      effect: "NoSchedule"

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - ingress-nginx
          topologyKey: kubernetes.io/hostname

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  config:
    use-real-ip: "true"
    proxy-body-size: "50m"
